### PR TITLE
Promote specifications to core aac language

### PR DESCRIPTION
**Pull request by jondavid-black**
This satisfied #558 by moving the schema definitions and validators out of the specifications first party plugin into the core language and validators respectively.

### CODE REVIEW

**Comment by cvchaparro** [comment]
@jondavid-black Since you created this PR, GitHub won't let me add you as a reviewer but since you were originally working this, I think it best to allow you to provide feedback, too. I think it's ready - please let me know if you have any comments/questions/concerns/etc.

**Comment by cvchaparro** [comment]
@coffee2bits @lizzcondrey @jondavid-black

Bump

**Review by Coffee2Bits — APPROVED** [review]
Looks good! Great job!

**Comment by jondavid-black** [comment]
Changes look good to me.  Thank you for finishing up this PR!

**Pull request merged**
